CREATE DATABASE RedeLojas

USE RedeLojas

CREATE TABLE Prestador(
ID BIGINT IDENTITY,
nome NVARCHAR(50) NOT NULL,
CONSTRAINT [FK_Suppliers] PRIMARY KEY CLUSTERED
(
	[ID] ASC
))
GO

CREATE TABLE Armazem(
ID BIGINT IDENTITY,
nome NVARCHAR(50) NOT NULL,
CONSTRAINT [FK_Stocks] PRIMARY KEY CLUSTERED
(
	[ID] ASC
))
GO

CREATE TABLE TipoTransacao(
ID BIGINT IDENTITY,
nome NVARCHAR(50) NOT NULL,
CONSTRAINT [FK_TransactionTypes] PRIMARY KEY CLUSTERED
(
	[ID] ASC
))
GO

CREATE TABLE Categoria(
ID BIGINT IDENTITY,
nome NVARCHAR(50) NOT NULL,
descricao NVARCHAR(100) NOT NULL,
CONSTRAINT [FK_Categoria] PRIMARY KEY CLUSTERED
(
	[ID] ASC
))
GO

/*
CREATE TABLE ItemPedido(
ID BIGINT IDENTITY,
pedidoId BIGINT NOT NULL,
itemId BIGINT NOT NULL,
numeroLote NVARCHAR(50),
quantidade DECIMAL(18,2) NOT NULL
CONSTRAINT [FK_Transactions] PRIMARY KEY CLUSTERED
(
	[ID] ASC
))
GO
*/

/*
CREATE TABLE Item(
ID BIGINT IDENTITY,
nome NVARCHAR(50) NOT NULL,
numeroLoteRequerido BIT,
quantidadeMinima BIGINT,
FornecedorID BIGINT,
CategoriaID BIGINT,
localID NCHAR(10),
CONSTRAINT [FK_Parts] PRIMARY KEY CLUSTERED
(
	[ID] ASC
))
GO
*/

/*
CREATE TABLE Pedido(
ID BIGINT IDENTITY,
tipoTransacaoID BIGINT,
transportadoraID BIGINT NOT NULL,
lojaID BIGINT NOT NULL,
armazemOrigemID BIGINT NOT NULL,
armazemDestinoID BIGINT NOT NULL,
DataPedido DATE NOT NULL,
DataEntrega DATE,
CONSTRAINT [FK_SupplierHeaders] PRIMARY KEY CLUSTERED
(
	[ID] ASC
))
GO
*/

CREATE TABLE ItemPedido(
ID BIGINT PRIMARY KEY IDENTITY,
pedidoId BIGINT,
itemId BIGINT,
numeroLote NVARCHAR(50) NULL,
quantidade DECIMAL(18,2))
GO

CREATE TABLE Pedido(
ID BIGINT PRIMARY KEY IDENTITY,
tipoTransacaoID BIGINT,
transportadoraID BIGINT NULL,
lojaID BIGINT NULL,
armazemOrigemID BIGINT NULL,
armazemDestinoID BIGINT NULL,
DataPedido DATE,
DataEntrega DATE NULL
)
GO

CREATE TABLE Item(
ID BIGINT PRIMARY KEY IDENTITY,
nome NVARCHAR(50),
numeroLoteRequerido BIT NULL,
quantidadeMinima BIGINT NULL,
FornecedorID BIGINT NULL,
CategoriaID BIGINT NULL,
localID NCHAR(10) NULL
)
GO


ALTER TABLE Item WITH CHECK ADD CONSTRAINT FK_Item_Armazem FOREIGN KEY(localID)
REFERENCES Armazem (ID)
GO
ALTER TABLE Item CHECK CONSTRAINT FK_Item_Armazem
GO
ALTER TABLE Item  WITH CHECK ADD  CONSTRAINT FK_Item_Categoria FOREIGN KEY(CategoriaID)
REFERENCES Categoria (ID)
GO
ALTER TABLE Item CHECK CONSTRAINT FK_Item_Categoria
GO
ALTER TABLE Item WITH CHECK ADD  CONSTRAINT FK_Item_Fornecedor FOREIGN KEY(FornecedorID)
REFERENCES Prestador (ID)
GO
ALTER TABLE Item CHECK CONSTRAINT FK_Item_Fornecedor
GO



ALTER TABLE ItemPedido  WITH CHECK ADD  CONSTRAINT FK_OrderItems_Orders FOREIGN KEY(pedidoID)
REFERENCES Pedido (ID)
GO

ALTER TABLE ItemPedido CHECK CONSTRAINT FK_OrderItems_Orders
GO
ALTER TABLE ItemPedido  WITH CHECK ADD  CONSTRAINT FK_Transactions_Parts FOREIGN KEY(itemID)
REFERENCES Item (ID)
GO
ALTER TABLE ItemPedido CHECK CONSTRAINT FK_Transactions_Parts
GO



ALTER TABLE Pedido  WITH CHECK ADD  CONSTRAINT FK_Headers_Stocks FOREIGN KEY(armazemOrigemID)
REFERENCES Armazem (ID)
GO
ALTER TABLE Pedido CHECK CONSTRAINT FK_Headers_Stocks
GO
ALTER TABLE Pedido  WITH CHECK ADD  CONSTRAINT FK_Headers_Stocks1 FOREIGN KEY(armazemDestinoID)
REFERENCES Armazem (ID)
GO
ALTER TABLE Pedido CHECK CONSTRAINT FK_Headers_Stocks1
GO
ALTER TABLE Pedido  WITH CHECK ADD  CONSTRAINT FK_Headers_TransactionTypes FOREIGN KEY(tipoTransacaoID)
REFERENCES TipoTransacao (ID)
GO
ALTER TABLE Pedido CHECK CONSTRAINT FK_Headers_TransactionTypes
GO
ALTER TABLE Pedido  WITH CHECK ADD  CONSTRAINT FK_Pedido_Fornecedor FOREIGN KEY(transportadoraID)
REFERENCES Prestador (ID)
GO
ALTER TABLE Pedido CHECK CONSTRAINT FK_Pedido_Fornecedor
GO
ALTER TABLE Pedido  WITH CHECK ADD  CONSTRAINT FK_Pedido_Prestador FOREIGN KEY(lojaID)
REFERENCES Prestador (ID)
GO
ALTER TABLE Pedido CHECK CONSTRAINT FK_Pedido_Prestador
GO






