CREATE DATABASE MensagemSensor;

USE MensagemSensor;

CREATE TABLE Recorde(
IdRecorde INT PRIMARY KEY IDENTITY,
Temperatura INT NOT NULL,
Marca INT NOT NULL
);

INSERT INTO Recorde VALUES (30,1);
INSERT INTO Recorde VALUES (30,1);
INSERT INTO Recorde VALUES (30,1);
INSERT INTO Recorde VALUES (32,2);
INSERT INTO Recorde VALUES (32,2);
INSERT INTO Recorde VALUES (32,2);
INSERT INTO Recorde VALUES (32,2);
INSERT INTO Recorde VALUES (30,3);
INSERT INTO Recorde VALUES (30,3);
INSERT INTO Recorde VALUES (30,3);
INSERT INTO Recorde VALUES (31,4);
INSERT INTO Recorde VALUES (31,4);
INSERT INTO Recorde VALUES (33,5);
INSERT INTO Recorde VALUES (33,5);
INSERT INTO Recorde VALUES (33,5);
INSERT INTO Recorde VALUES (33,5);

SELECT COUNT(Temperatura), Marca AS 'Numero de Recordes' FROM Recorde
WHERE Temperatura =30;

select * from recorde;